spring:
  application:
    name: greet-zuul-service

zuul:  prefix: /gateway
  routes:    GREET_SERVER:
        path: /sleuth-server/**
        url: http://localhost:8193
        service-id: greet-server
    GREET_CLIENT:
        path: /sleuth-client/**
        url: http://localhost:8192
        service-id: greet-client
server:
  port: 8194
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
